/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAO;
import Models.HoKhau;
import Models.NhanKhau;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dangdinhtho
 */
public class ThemNhanKhau extends javax.swing.JFrame {

    /**
     * Creates new form ThemNhanKhau
     */
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    private int action = 0;
    private boolean dkTamTru;
    private NhanKhau nhanKhauThem = new NhanKhau();
    private HoKhau hoKhau;
    private DAO dao = new DAO();

    public ThemNhanKhau(int action, String soHoKhau) {
        initComponents();
        this.action = action;

        if (action == 1) {
            lbThemNhanKhau.setText("THÊM CHỦ HỘ");
            txtQuanHeVoiChuHo.setText("Chủ hộ");
            txtQuanHeVoiChuHo.setEnabled(false);
        } else if (action == 3) {
            lbThemNhanKhau.setText("THÊM CHỦ HỘ (TẠM TRÚ)");
            txtQuanHeVoiChuHo.setText("Chủ hộ");
            txtQuanHeVoiChuHo.setEnabled(false);
            dkTamTru = true;
        } else {
            lbThemNhanKhau.setText("THÊM NHÂN KHẨU ");
            nhanKhauThem.setSoHoKhau(soHoKhau);
            hoKhau = dao.getHoKhau(soHoKhau);

            // System.out.println("them nhan khau");
        }

    }

    /* public ThemNhanKhau(){
     initComponents();
     lbThemNhanKhau.setText("ĐĂNG KÍ TẠM TRÚ");
     txtQuanHeVoiChuHo.setEnabled(false);
     dkTamTru = true;
     action = 3;
     } */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThemNhanKhau = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtBiDanh = new javax.swing.JTextField();
        txtNgheNghiep = new javax.swing.JTextField();
        txtNoiLamViec = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtDanToc = new javax.swing.JTextField();
        txtQuanHeVoiChuHo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        txtNoiTTTruocKhiDen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTonGiao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbThemNhanKhau.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbThemNhanKhau.setText("THÊM NHÂN KHẨU");

        jLabel16.setText("Quan hệ với chủ hộ*:");

        jLabel2.setText("Họ tên*:");

        txtNgaySinh.setToolTipText("Định dạng ngày sinh dd/mm/yyyy ");

        jLabel3.setText("Bí danh:");

        jLabel4.setText("Ngày sinh*:");

        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel7.setText("Giới tính*:");

        jLabel8.setText("Quê quán*:");

        jLabel9.setText("Dân tộc*:");

        jLabel11.setText("Nghề nghiệp:");

        jLabel12.setText("Nơi làm việc:");

        jLabel13.setText("CMND:");

        lab.setText("Nơi Thường trú trước khi chuyển đến:");

        jLabel1.setText("Tôn giáo*:");

        jLabel5.setText("(Các trường đánh dấu * là bắt buộc)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnXacNhan))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbThemNhanKhau)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtBiDanh)
                                .addComponent(txtNgaySinh)
                                .addComponent(txtGioiTinh)
                                .addComponent(txtQueQuan)
                                .addComponent(txtDanToc)
                                .addComponent(txtNgheNghiep)
                                .addComponent(txtNoiLamViec)
                                .addComponent(txtQuanHeVoiChuHo)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(6, 280, Short.MAX_VALUE)
                                    .addComponent(btnHuy))
                                .addComponent(txtTonGiao)
                                .addComponent(txtHoTen)
                                .addComponent(txtNoiTTTruocKhiDen)
                                .addComponent(txtCMND)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbThemNhanKhau)
                        .addGap(38, 38, 38)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBiDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab)
                    .addComponent(txtNoiTTTruocKhiDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(txtQuanHeVoiChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (!txtCMND.getText().equals("") && dao.CheckHaveNhanKhau(txtCMND.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Nhân khẩu mang số CMND " + txtCMND.getText()
                    + " đã tồn tại\nKiểm tra lại!");
        } else if (action == 1) {
            ThemChuHo();
        } else if (action == 2) {
            ThemNhanKhauMoi();
        } else if (action == 3) {
            DangKhiTamTru();
        }

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    public void ThemChuHo() {

        try {
            nhanKhauThem.setHoTen(txtHoTen.getText());
            nhanKhauThem.setBiDanh(txtBiDanh.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            nhanKhauThem.setNgaysinh(sdf.parse(txtNgaySinh.getText()));
            nhanKhauThem.setGioiTinh(txtGioiTinh.getText());
            nhanKhauThem.setQueQuan(txtQueQuan.getText());
            nhanKhauThem.setDanToc(txtDanToc.getText());
            nhanKhauThem.setTonGiao(txtTonGiao.getText());
            //nhanKhauThem.setNgayChuyenDen(new Date());
            nhanKhauThem.setNoiTTTruocKhiChuyenDen(txtNoiTTTruocKhiDen.getText());
            nhanKhauThem.setCMND(txtCMND.getText());
            nhanKhauThem.setNgheNghiep(txtNgheNghiep.getText());
            nhanKhauThem.setQuanHeVoiChuHo("Chủ hộ");
            nhanKhauThem.setChuHo(true);

        } catch (Exception e) {
            System.out.println(e);
        }

        if (!checkNull()) {
            JOptionPane.showMessageDialog(null, "Các trường đánh dấu * không được để trống");

        } else {
            new ThemHoKhau(nhanKhauThem).setVisible(true);
            this.setVisible(false);
        }

    }

    public void ThemNhanKhauMoi() {
        try {
            nhanKhauThem.setHoTen(txtHoTen.getText());
            nhanKhauThem.setBiDanh(txtBiDanh.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            nhanKhauThem.setNgaysinh(sdf.parse(txtNgaySinh.getText()));
            nhanKhauThem.setGioiTinh(txtGioiTinh.getText());
            nhanKhauThem.setQueQuan(txtQueQuan.getText());
            nhanKhauThem.setDanToc(txtDanToc.getText());
            nhanKhauThem.setTonGiao(txtTonGiao.getText());
            //nhanKhauThem.setNgayChuyenDen(new Date());
            nhanKhauThem.setNoiTTTruocKhiChuyenDen(txtNoiTTTruocKhiDen.getText());
            nhanKhauThem.setCMND(txtCMND.getText());
            nhanKhauThem.setNgheNghiep(txtNgheNghiep.getText());
            nhanKhauThem.setQuanHeVoiChuHo(txtQuanHeVoiChuHo.getText());
            nhanKhauThem.setChuHo(false);

        } catch (Exception e) {
            System.out.println(e);
        }

        if (!checkNull()) {
            JOptionPane.showMessageDialog(null, "Các trường đánh dấu * không được để trống");

        } else {
            hoKhau.setLichSuChinhSua("*" + dateFormat.format(new Date()) + ": \n" + "- Thêm nhân khẩu: " + nhanKhauThem.getHoTen() + " vào hộ khẩu.\n");

            boolean done = dao.ThemNhanKhau(nhanKhauThem);
            done = dao.SuaHoKhau(hoKhau);

        //ArrayList<NhanKhau> nhanKhaus = hoKhau.getDsNhanKhaus();
            //nhanKhaus.add(nhanKhauThem);
            hoKhau = dao.getHoKhau(hoKhau.getSoHoKhau());

            if (done) {
                int click = JOptionPane.showConfirmDialog(null, "Thêm nhân khẩu thành công.\n Tiếp tục thêm nhân khẩu khác vào hộ khẩu này? ", "", JOptionPane.YES_NO_OPTION);
                if (click == JOptionPane.YES_OPTION) {
                    resetForm();
                } else {
                    new XemTTHoKhau(hoKhau).setVisible(true);
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Thêm nhân khẩu thất bại.");
            }
        }

    }

    public void DangKhiTamTru() {
        try {
            nhanKhauThem.setHoTen(txtHoTen.getText());
            nhanKhauThem.setBiDanh(txtBiDanh.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            nhanKhauThem.setNgaysinh(sdf.parse(txtNgaySinh.getText()));
            nhanKhauThem.setGioiTinh(txtGioiTinh.getText());
            nhanKhauThem.setQueQuan(txtQueQuan.getText());
            nhanKhauThem.setDanToc(txtDanToc.getText());
            nhanKhauThem.setTonGiao(txtTonGiao.getText());
            nhanKhauThem.setNgayChuyenDen(new Date());
            nhanKhauThem.setNoiTTTruocKhiChuyenDen(txtNoiTTTruocKhiDen.getText());
            nhanKhauThem.setCMND(txtCMND.getText());
            nhanKhauThem.setNgheNghiep(txtNgheNghiep.getText());
            nhanKhauThem.setTamTru(true);
            nhanKhauThem.setChuHo(false);

        } catch (Exception e) {
            System.out.println(e);
        }
        if (!checkNull()) {
            JOptionPane.showMessageDialog(null, "Các trường đánh dấu * không được để trống");

        } else {
            new ThemHoKhau(nhanKhauThem).setVisible(true);
            this.setVisible(false);
        }

    }

    public void resetForm() {

        txtBiDanh.setText(null);
        txtCMND.setText(null);
        txtDanToc.setText(null);
        txtGioiTinh.setText(null);
        txtHoTen.setText(null);
        txtTonGiao.setText(null);
        txtQuanHeVoiChuHo.setText(null);
        txtNgaySinh.setText(null);
        txtNgheNghiep.setText(null);
        txtNoiLamViec.setText(null);
        txtQueQuan.setText(null);
        txtNoiTTTruocKhiDen.setText(null);
       

    }

    public boolean checkNull() {

        if (txtHoTen.getText().equals("")) {
            return false;
        }
        if (txtDanToc.getText().equals("")) {
            return false;
        }
        if (txtGioiTinh.getText().equals("")) {
            return false;
        }
        if (txtNgaySinh.getText().equals("")) {
            return false;
        }
        if (txtTonGiao.getText().equals("")) {
            return false;
        }
        if (txtQueQuan.getText().equals("")) {
            return false;
        }
        if (txtQuanHeVoiChuHo.getText().equals("")) {
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel lbThemNhanKhau;
    private javax.swing.JTextField txtBiDanh;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDanToc;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgheNghiep;
    private javax.swing.JTextField txtNoiLamViec;
    private javax.swing.JTextField txtNoiTTTruocKhiDen;
    private javax.swing.JTextField txtQuanHeVoiChuHo;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTonGiao;
    // End of variables declaration//GEN-END:variables
}
