/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DAO;
import Models.HoKhau;
import Models.NhanKhau;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dangdinhtho
 */
public class XemTTNhanKhau extends javax.swing.JFrame {

    /**
     * Creates new form XemTTNhanKhau
     *
     */
    private NhanKhau nhanKhau = new NhanKhau();
    private DAO dao = new DAO();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    public XemTTNhanKhau(NhanKhau nhanKhau) {

        // hiển thị các thông tin lên giao diện 
        
        this.nhanKhau = nhanKhau;
        initComponents();
        txtHoTen.setText(nhanKhau.getHoTen());
        txtBiDanh.setText(nhanKhau.getBiDanh());

        txtNgaySinh.setText(dateFormat.format(nhanKhau.getNgaysinh()));
        txtGioiTinh.setText(nhanKhau.getGioiTinh());
        txtQueQuan.setText(nhanKhau.getQueQuan());
        txtDanToc.setText(nhanKhau.getDanToc());
        txtTonGiao.setText(nhanKhau.getTonGiao());
        txtNgheNghiep.setText(nhanKhau.getNgheNghiep());
        txtNoiLamViec.setText("");
        txtCMND.setText(nhanKhau.getCMND());
        if (nhanKhau.getNgayChuyenDen() != null) {
            txtNgayDKHKTT.setText(dateFormat.format(nhanKhau.getNgayChuyenDen()));
        }
        txtDiaChiTTTruocKhiDen.setText(nhanKhau.getNoiTTTruocKhiChuyenDen());
        txtQuanHeVoiChuHo.setText(nhanKhau.getQuanHeVoiChuHo());
        txtLichSuChinhSua.setText(nhanKhau.getLichSuChinhSua());
        if (nhanKhau.getNgayChuyenDi()!= null)
            txtNgayChuyenDI.setText(dateFormat.format(nhanKhau.getNgayChuyenDi()));
        txtNoiChuyenDi.setText(nhanKhau.getNoiChuyenDi());
        txtLiDoChuyenDi.setText(nhanKhau.getLiDoChuyenDi());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThayDoi = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnXemHoKhau = new javax.swing.JButton();
        btnBaoTu = new javax.swing.JButton();
        btnDKTamVang = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbNgayChuyenDi = new javax.swing.JLabel();
        lbNoiChuyenDi = new javax.swing.JLabel();
        lbLiDoChuyenDi = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtGioiTinh = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtDanToc = new javax.swing.JTextField();
        txtTonGiao = new javax.swing.JTextField();
        txtNgheNghiep = new javax.swing.JTextField();
        txtNoiLamViec = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtNgayDKHKTT = new javax.swing.JTextField();
        txtDiaChiTTTruocKhiDen = new javax.swing.JTextField();
        txtQuanHeVoiChuHo = new javax.swing.JTextField();
        txtNgayChuyenDI = new javax.swing.JTextField();
        txtNoiChuyenDi = new javax.swing.JTextField();
        txtLiDoChuyenDi = new javax.swing.JTextField();
        txtBiDanh = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLichSuChinhSua = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN KHẨU");

        btnThayDoi.setText("Chỉnh sửa");
        btnThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiActionPerformed(evt);
            }
        });

        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXemHoKhau.setText("Xem Hộ Khẩu");
        btnXemHoKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemHoKhauActionPerformed(evt);
            }
        });

        btnBaoTu.setText("Báo tử");
        btnBaoTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoTuActionPerformed(evt);
            }
        });

        btnDKTamVang.setText("Đăng kí tạm vắng");
        btnDKTamVang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKTamVangActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận ");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Bí danh:");

        jLabel4.setText("Ngày sinh:");

        jLabel7.setText("Giới tính:");

        jLabel8.setText("Quê quán:");

        jLabel9.setText("Dân tộc:");

        jLabel6.setText("Tôn Giáo:");

        jLabel11.setText("Nghề nghiệp:");

        jLabel12.setText("Nơi làm việc:");

        jLabel13.setText("CMND:");

        jLabel16.setText("Địa chỉ TT trước khi chuyển đến:");

        jLabel5.setText("Quan hệ với chủ hộ:");

        lbNgayChuyenDi.setText("Ngày chuyển đi:");

        lbNoiChuyenDi.setText("Nơi chuyển đi:");

        lbLiDoChuyenDi.setText("Lí do chuyển đi:");

        txtHoTen.setEditable(false);
        txtHoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoTenKeyReleased(evt);
            }
        });

        txtNgaySinh.setEditable(false);

        txtGioiTinh.setEditable(false);

        txtQueQuan.setEditable(false);

        txtDanToc.setEditable(false);

        txtTonGiao.setEditable(false);

        txtNgheNghiep.setEditable(false);

        txtNoiLamViec.setEditable(false);

        txtCMND.setEditable(false);

        txtNgayDKHKTT.setEditable(false);

        txtDiaChiTTTruocKhiDen.setEditable(false);

        txtQuanHeVoiChuHo.setEditable(false);

        txtNgayChuyenDI.setEditable(false);

        txtNoiChuyenDi.setEditable(false);

        txtLiDoChuyenDi.setEditable(false);

        txtBiDanh.setEditable(false);
        txtBiDanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiDanhActionPerformed(evt);
            }
        });
        txtBiDanh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBiDanhKeyReleased(evt);
            }
        });

        jLabel15.setText("Ngày ĐK HKTT:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(txtNgaySinh)
                            .addComponent(txtDanToc)
                            .addComponent(txtTonGiao)
                            .addComponent(txtNgheNghiep)
                            .addComponent(txtNoiLamViec)
                            .addComponent(txtCMND)
                            .addComponent(txtBiDanh)
                            .addComponent(txtQueQuan)
                            .addComponent(txtHoTen)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNoiChuyenDi)
                            .addComponent(lbLiDoChuyenDi)
                            .addComponent(lbNgayChuyenDi)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLiDoChuyenDi)
                            .addComponent(txtNgayChuyenDI)
                            .addComponent(txtQuanHeVoiChuHo)
                            .addComponent(txtNoiChuyenDi)
                            .addComponent(txtDiaChiTTTruocKhiDen)
                            .addComponent(txtNgayDKHKTT)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBiDanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTonGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayDKHKTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDiaChiTTTruocKhiDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuanHeVoiChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayChuyenDi)
                    .addComponent(txtNgayChuyenDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNoiChuyenDi)
                    .addComponent(txtNoiChuyenDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLiDoChuyenDi)
                    .addComponent(txtLiDoChuyenDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtLichSuChinhSua.setEditable(false);
        txtLichSuChinhSua.setColumns(20);
        txtLichSuChinhSua.setRows(5);
        jScrollPane1.setViewportView(txtLichSuChinhSua);

        jLabel10.setText("LỊCH SỬ CHỈNH SỬA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnXemHoKhau)
                .addGap(165, 165, 165)
                .addComponent(btnThayDoi)
                .addGap(18, 18, 18)
                .addComponent(btnDKTamVang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBaoTu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXacNhan)
                .addGap(33, 33, 33)
                .addComponent(btnHuy)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemHoKhau)
                    .addComponent(btnHuy)
                    .addComponent(btnThayDoi)
                    .addComponent(btnBaoTu)
                    .addComponent(btnDKTamVang)
                    .addComponent(btnXacNhan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
       
        this.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed


    private void btnThayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiActionPerformed
        // TODO add your handling code here:

        // khi nhấn nút thay đổi thông tin nhân khẩu thì các TextField sẽ cho phép sửa dữ liệu 
        
        txtBiDanh.setEditable(true);
        txtCMND.setEditable(false);
        txtDanToc.setEditable(true);
        txtGioiTinh.setEditable(true);
        txtHoTen.setEditable(true);
        txtTonGiao.setEditable(true);
        //txtNgayDKHKTT.setEditable(true);
        //txtNgaySinh.setEditable(true);
        txtNgheNghiep.setEditable(true);

        txtNoiLamViec.setEditable(true);

        //txtQueQuan.setEditable(true);
        //txtDiaChiTTTruocKhiDen.setEditable(true);
        txtQuanHeVoiChuHo.setEditable(true);

        //btnThayDoi.setText("Xác nhận thay đổi");
        changed = 1;

    }//GEN-LAST:event_btnThayDoiActionPerformed

    private void btnXemHoKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemHoKhauActionPerformed
        // TODO add your handling code here:
        if(nhanKhau.isTamTru()){
            JOptionPane.showMessageDialog(null, "Đây là nhân khẩu tạm trú");
        }
        else{
            HoKhau hoKhau = new DAO().getHoKhau(nhanKhau.getSoHoKhau());    // Lấy hộ khẩu chứa nhân khẩu trên CSDL .
            new XemTTHoKhau(hoKhau).setVisible(true);  // mở cửa sổ xem hộ khẩu của nhân khẩu này bằng cách gọi đối tượng new XEmTTHoKhau với tham số truyền vào là sổ hộ khẩu vừa lấy ở dòng trên.
        }
    }//GEN-LAST:event_btnXemHoKhauActionPerformed

    private void btnBaoTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoTuActionPerformed
        // TODO add your handling code here:
        // Chọn báo tử thì dòng ngày chuyển đi sẽ cho phép chỉnh sửa thông tin.
        txtNgayChuyenDI.setEditable(true);
        //txtLiDoChuyenDi.setEditable(true);
        changed = 2;

    }//GEN-LAST:event_btnBaoTuActionPerformed

    private void btnDKTamVangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKTamVangActionPerformed
        // TODO add your handling code here:
        
        txtNgayChuyenDI.setEditable(true);
        txtNoiChuyenDi.setEditable(true);
        txtLiDoChuyenDi.setEditable(true);
        changed = 3;
    }//GEN-LAST:event_btnDKTamVangActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        switch (changed) {     // biến change với các giá trị 1,2,3 tương ứng là thay đổi thông tin nhân khẩu, báo tử hay đăng ký tạm vắng 
            case 1: {

                boolean isChange = false;
                String thayDoi;
                thayDoi = dateFormat.format(new Date()) + ": \n";
                if (!nhanKhau.getHoTen().equals(txtHoTen.getText())) {
                    thayDoi += "- Thay đổi họ tên từ: \"" + nhanKhau.getHoTen() + "\" thành \"" + txtHoTen.getText() + "\"\n";

                    isChange = true;

                }
                if ((nhanKhau.getBiDanh() != null && !nhanKhau.getBiDanh().equals(txtBiDanh.getText())) || (nhanKhau.getBiDanh() == null && !txtBiDanh.getText().equals(""))) {
                    thayDoi += "- Thay đổi bí danh từ: \"" + nhanKhau.getBiDanh() + "\" thành \"" + txtBiDanh.getText() + "\"\n";

                    isChange = true;
                }
                if (!nhanKhau.getGioiTinh().equals(txtGioiTinh.getText())) {
                    thayDoi += "- Thay đổi giới tính từ: \"" + nhanKhau.getGioiTinh() + "\" thành \"" + txtGioiTinh.getText() + "\"\n";

                    isChange = true;
                }
                if (!nhanKhau.getTonGiao().equals(txtTonGiao.getText())) {
                    thayDoi += "- Thay đổi tôn giáo từ: \"" + nhanKhau.getGioiTinh() + "\" thành \"" + txtGioiTinh.getText() + "\"\n";

                    isChange = true;
                }
                if ((nhanKhau.getNgheNghiep() != null && !nhanKhau.getNgheNghiep().equals(txtNgheNghiep.getText())) || (nhanKhau.getNgheNghiep() == null && !txtNgheNghiep.getText().equals(""))) {
                    thayDoi += "- Thay đổi nghề nghiệp từ: \"" + nhanKhau.getNgheNghiep() + "\" thành \"" + txtNgheNghiep.getText() + "\"\n";

                    isChange = true;
                }
                //if (!nhanKhau.getQuanHeVoiChuHo().equals(txtQuanHeVoiChuHo.getText())) {
                    //thayDoi += "- Thay đổi quan hệ với chủ hộ từ: \"" + nhanKhau.getQuanHeVoiChuHo() + "\" thành \"" + txtQuanHeVoiChuHo.getText() + "\"\n";

                   //isChange = true;
                //}
                if (!isChange) {
                    thayDoi = null;
                    return;
                }

                int click = JOptionPane.showConfirmDialog(null, "Xác nhận thay đổi thông tin nhân khẩu: \n" + thayDoi, "", JOptionPane.YES_NO_OPTION);
                if (click == JOptionPane.YES_OPTION) {

                    nhanKhau.setHoTen(txtHoTen.getText());
                    nhanKhau.setBiDanh(txtBiDanh.getText());
                    nhanKhau.setGioiTinh(txtGioiTinh.getText());
                    nhanKhau.setTonGiao(txtTonGiao.getText());
                    nhanKhau.setNgheNghiep(txtNgheNghiep.getText());
                    nhanKhau.setQuanHeVoiChuHo(txtQuanHeVoiChuHo.getText());
                    nhanKhau.setLichSuChinhSua(thayDoi);

                    boolean done = dao.SuaNhanKhau(nhanKhau);
                    if (done) {
                        JOptionPane.showMessageDialog(null, "Cập nhật thông tin nhân khẩu thành công.");
                        txtLichSuChinhSua.setText(nhanKhau.getLichSuChinhSua());
                    } else {
                        JOptionPane.showMessageDialog(null, "Cập nhật thông tin nhân khẩu thất bại.");
                    }

                } else {
                    //this.setVisible(false);
                }
                break;
            }

            case 2: {
                
                int click = JOptionPane.showConfirmDialog(null, "Xác nhận báo tử nhân khẩu: " + txtHoTen.getText(), "", JOptionPane.YES_NO_OPTION);
                if (click == JOptionPane.YES_OPTION) {

                    try {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        nhanKhau.setNgayChuyenDi(sdf.parse(txtNgayChuyenDI.getText()));
                        nhanKhau.setDaMat(true);
                        nhanKhau.setLichSuChinhSua(dateFormat.format(new Date()) + ": \n" + "- Báo tử \n");
                    } catch (Exception e) {
                    }
                    

                    boolean done = dao.SuaNhanKhau(nhanKhau);
                    if (done) {
                        JOptionPane.showMessageDialog(null, "Báo tử thành công.");
                        txtLichSuChinhSua.setText(nhanKhau.getLichSuChinhSua());
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, hãy thử lại.");
                    }

                } else {
                    //this.setVisible(false);
                }
                
                
                break;
            }
            case 3: {
                
                int click = JOptionPane.showConfirmDialog(null, "Xác nhận đăng kí tạm vắng: " + txtHoTen.getText(), "", JOptionPane.YES_NO_OPTION);
                if (click == JOptionPane.YES_OPTION) {

                    try {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                        nhanKhau.setNgayChuyenDi(sdf.parse(txtNgayChuyenDI.getText()));
                        nhanKhau.setNoiChuyenDi(txtNoiChuyenDi.getText());
                        nhanKhau.setLiDoChuyenDi(txtLiDoChuyenDi.getText());
                        nhanKhau.setLichSuChinhSua(dateFormat.format(new Date()) + ": \n" + "- Đăng kí tạm vắng \n");
                    } catch (Exception e) {
                    }
                    

                    boolean done = dao.SuaNhanKhau(nhanKhau);
                    if (done) {
                        JOptionPane.showMessageDialog(null, "Đăng kí tạm vắng thành công.");
                        txtLichSuChinhSua.setText(nhanKhau.getLichSuChinhSua());
                    } else {
                        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra, hãy thử lại.");
                    }

                } else {
                    //this.setVisible(false);
                }
                
                break;

            }
        }

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void txtBiDanhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiDanhKeyReleased
        // TODO add your handling code here:
        Changed();
    }//GEN-LAST:event_txtBiDanhKeyReleased

    private void txtBiDanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiDanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiDanhActionPerformed

    private void txtHoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoTenKeyReleased
        // TODO add your handling code here:
        Changed();
    }//GEN-LAST:event_txtHoTenKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemTTNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemTTNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemTTNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemTTNhanKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new XemTTNhanKhau().setVisible(true);

            }
        });

    }

    private void Changed() {

    }

    private int changed = 0;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoTu;
    private javax.swing.JButton btnDKTamVang;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThayDoi;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXemHoKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLiDoChuyenDi;
    private javax.swing.JLabel lbNgayChuyenDi;
    private javax.swing.JLabel lbNoiChuyenDi;
    private javax.swing.JTextField txtBiDanh;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDanToc;
    private javax.swing.JTextField txtDiaChiTTTruocKhiDen;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLiDoChuyenDi;
    private javax.swing.JTextArea txtLichSuChinhSua;
    private javax.swing.JTextField txtNgayChuyenDI;
    private javax.swing.JTextField txtNgayDKHKTT;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgheNghiep;
    private javax.swing.JTextField txtNoiChuyenDi;
    private javax.swing.JTextField txtNoiLamViec;
    private javax.swing.JTextField txtQuanHeVoiChuHo;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTonGiao;
    // End of variables declaration//GEN-END:variables
}
